//
//  DataSource.m
//  TableViewHomework
//
//  Created by abyssinaong on 2017. 2. 19..
//  Copyright © 2017년 KimYunseo. All rights reserved.
//

#import "DataSource.h"
@interface DataSource()



@end

@implementation DataSource


- (instancetype)initArray
{
    self = [super init];
    if (self) {
        

        self.name = @[@"Stephou Dcqr",
                      @"Jordy van Osch",
                      @"Vincent Schaap",
                      @"Alvaro Sanz",
                      @"Dominic & Jeanine",
                      @"Rein Rijke",
                      @"Katja van Hoorn",
                      @"Max Muench",
                      @"Saar & Paul",
                      @"Lisanne Beijen",
                      @"Eddie De Vries",
                      @"Michæl Schulenburg",
                      @"Charlotte de Vries",
                      @"Joyce Kooren",
                      @"Adam and Bex",
                      @"Niek Bokkers",
                      @"Maud van Woerden",
                      @"Vivianne Zhong",
                      @"Laser Unicorns",
                      @"Freddi Woomba",
                      @"Bert Kuiper",
                      @"Duncan Allardyce",
                      @"Lianne van Vliet",
                      @"Ronald en Corrie Witte/Kaptein",
                      @"Nadine",
                      @"Max Muench",
                      @"Jelle Mol"];
        
        
        self.nation = @[@"Ottignies-Louvain-la-Neuve, Belgium",
                        @"Emmen, Nederland",
                        @"London, United Kingdom",
                        @"Seoul, Korea",
                        @"Harlingen, Nederland",
                        @"Utrecht, Netherlands",
                        @"Göteborg, Sverige",
                        @"Göteborg, Sverige",
                        @"Utrecht, Nederland",
                        @"Utrecht, Nederland",
                        @"Utrecht, Nederland",
                        @"Amsterdam, Netherlands",
                        @"Amsterdam, Netherlands",
                        @"New Zealand, New Zealand",
                        @"New Zealand, New Zealand",
                        @"Utrecht, Netherlands",
                        @"Emmen, Nederland",
                        @"Göteborg, Sverige",
                        @"Amsterdam, Netherlands",
                        @"Lelystad, Nederland",
                        @"Lelystad, Nederland",
                        @"London, United Kingdom",
                        @"Amsterdam, Netherlands",
                        @"Bentveld, Nederland",
                        @"Göteborg, Sverige",
                        @"Bentveld, Nederland",
                        @"Amsterdam, Netherlands"
                        ];
        
        self.title = @[@"Mission Madagascar",
                       @"Namibia and Botswana uncovered",
                       @"New Zealand. Indonesia. Malaysia.",
                       @"Antarctica, exploring the South Pole",
                       @"South Africa - East & Western Cape",
                       @"The Nomads Bus",
                       @"Iran, Armenia and Georgia",
                       @"Mongolia",
                       @"Cape Town to Patagonia",
                       @"One way ticket to the Far East",
                       @"Nepal on a Royal Enfield",
                       @"The Orient encompassed",
                       @"Ethiopia; a hidden gem",
                       @"Paradise is now...",
                       @"8 months in LatAm, still no beard?",
                       @"Paddling through The Netherlands",
                       @"Roadtrip Scandinavia",
                       @"Skipping school for Central America",
                       @"Amsterdam Dakar Challenge",
                       @"A Transcontinental Euro-African Hitch",
                       @"Cycling to Santiago de Compostella",
                       @"The Americas on a shoestring",
                       @"Backpacking South America",
                       @"Exploring the Silk Road",
                       @"The Pacific Islands and Oceania",
                       @"Jordan",
                       @"Around the world sabbatical!"];
        
        self.year = @[@"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2016",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2015",
                      @"2014",
                      @"2014"];
        
        self.month = @[@"june",
                       @"june",
                       @"june",
                       @"may",
                       @"july",
                       @"february",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"august",
                       @"june",
                       @"june",
                       @"june",
                       @"october",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june",
                       @"june"];
        self.days = @[@"67",
                      @"27",
                      @"34",
                      @"32",
                      @"54",
                      @"16",
                      @"45",
                      @"52",
                      @"73",
                      @"26",
                      @"38",
                      @"48",
                      @"26",
                      @"58",
                      @"98",
                      @"67",
                      @"67",
                      @"67",
                      @"67",
                      @"67",
                      @"67",
                      @"67",
                      @"46",
                      @"21",
                      @"40",
                      @"32",
                      @"60"];
        
        self.kilometer = @[@"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746",
                           @"23,746"];
        
        self.steps = @[@"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45",
                       @"45"];
        
        self.explain = @[@"Work and pleasure combined on the most beatiful island in the world!",
                         @"A beautiful wilderness safari through the Kalahari desert and Okavango Delta",
                         @"First stop: visiting the 'land of the long white cloud'",
                         @"A tale about history, photography and the lighthouse at the end of the world",
                         @"Whale watching, wine farms, the big 5, skydiving. All of this packed in 3 weeks!",
                         @"Rein spent a few nights in this hostel on wheels. We're a big fan of this concept!",
                         @"I just loved these beautiful and insanely interesting countries full of contradictions",
                         @"Roaming the Mongolian steppes and crossing the Gobi desert like a true nomad.",
                         @"Adventurous couple + a passion for photography = an incredibly appealing read!",
                         @"Asia is where the heart is. Lisanne strolling through China, Laos, Myanmar...",
                         @"The days on the Annapurna trails were the best I ever had on a motorcycle!",
                         @"SE Asia. Where you'll find the stunningest beaches and jungles of 'm all!",
                         @"For sure one of the most diverse countries you will ever visit",
                         @"Exploring and enjoying Asia to the fullest!",
                         @"Amazingly colorful write-up of this venture to South America",
                         @"Small trips can be adventurous too! Canoeing the rivers of The Netherlands",
                         @"Hipster family steering their camper through the rough lands of Scandinavia",
                         @"Rice, beans & learning spanish: 'Mi caballo no come arroz'",
                         @"Driving a 500 euro car or bike from NL to Dakar - Senegal; quite the adventure!",
                         @"The ultimate hitchiking tale; Freddi's ongoing journey discovering Europe",
                         @"Duo that tackles the famous pilgrimage route Camino de Santiago on a bicycle",
                         @"Using Polarsteps without a smartphone? This trip shows you what that looks like!",
                         @"Solo travel junkie getting the most out of Latin America. No te lo pierdas!",
                         @"This famous trade route is one of the most popular journeys by overlanders",
                         @"100+ days voyage to see the other side of the world",
                         @"Check out these jaw dropping photos by a Berlin based travel photographer",
                         @"Europe, the Middle East and partying all across the globe ;-)"
                         ];
        
        self.dataSet = @[@{@"name":self.name},
                         @{@"nation":self.nation},
                         @{@"title":self.title},
                         @{@"year":self.year},
                         @{@"month":self.month},
                         @{@"days":self.days},
                         @{@"kilometer":self.kilometer},
                         @{@"steps":self.steps},
                         @{@"explain":self.explain}];
        

    }
    
    return self;
}


@end
